# Generated by Django 4.2.1 on 2023-06-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingredient1', models.ManyToManyField(related_name='i1', to='learning_api.ingredient')),
                ('ingredient2', models.ManyToManyField(related_name='i2', to='learning_api.ingredient')),
            ],
        ),
    ]
