# Generated by Django 4.2.1 on 2023-06-20 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_api', '0002_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient1',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient2',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i1', to='learning_api.ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i2', to='learning_api.ingredient'),
        ),
    ]
